export const SET_PHONE = 'SET_PHONE'
export const LOGOUT = 'LOGOUT'
export const SET_USER = 'SET_USER'

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST'
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS'
export const SEND_CODE_FAILURE = 'SEND_CODE_FAILURE'

export const CHECK_PHONE_REQUEST = 'CHECK_PHONE_REQUEST'
export const CHECK_PHONE_SUCCESS = 'CHECK_PHONE_SUCCESS'
export const CHECK_PHONE_FAILURE = 'CHECK_PHONE_FAILURE'

export const CLEAR_MODULE = 'CLEAR_MODULE'

export default {
  SET_PHONE,
  LOGOUT,
  SET_USER,
  SIGN_IN_REQUEST,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
  SEND_CODE_REQUEST,
  SEND_CODE_SUCCESS,
  SEND_CODE_FAILURE,
  CHECK_PHONE_REQUEST,
  CHECK_PHONE_SUCCESS,
  CHECK_PHONE_FAILURE,
  CLEAR_MODULE
}
